### ISSUE TITLE
imports github.com/opennota/check/cmd/defercheck

### ISSUE THREAD

**Issue by p4ntek** [mtojek/go-url-fuzzer#1]
"imports github.com/opennota/check/cmd/defercheck
	imports github.com/opennota/check/cmd/defercheck: cannot find package "github.com/opennota/check/cmd/defercheck" in any of:
	/usr/lib/go/src/pkg/github.com/opennota/check/cmd/defercheck (from $GOROOT)
	/usr/share/go/src/github.com/opennota/check/cmd/defercheck (from $GOPATH)
make: *** [go-get] Błąd 1"

Tam nie ma takiego katologu:
https://github.com/opennota/check/tree/master/cmd
Chyba, że nie w tym rzecz.
Edit:
Faktycznie usunęli:
https://github.com/opennota/check/commit/aa37591a11986c7dd6ce70640271a752b37b0ea2

**Comment by mtojek** [comment]
Fixed, dziękuję za zgłoszenie :)
